In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

In [2]:
A = np.random.randn(100)

In [3]:
A

array([-1.26153784, -1.68104463,  1.15341527, -0.10595896,  0.03852408,
        1.50399716, -0.32277676,  0.8258373 ,  0.70938431, -0.19508667,
        1.85863897,  1.08779747, -1.22372806, -0.16987016,  1.4738026 ,
        0.23389452, -0.67180789, -0.08688614,  1.47195698,  0.7147902 ,
        0.55923614, -1.15939488,  0.79665542,  0.04895139,  0.6244977 ,
       -0.54650397,  0.29459478,  0.44576687,  1.01622044,  0.07997326,
       -1.99128267,  1.1377457 , -1.20875086, -0.63127756,  0.45046332,
        0.33253222, -0.13090554,  0.31252861,  1.07417164, -1.95056305,
        1.10445206, -0.60287408, -0.65303511,  0.17784573, -0.68486593,
       -1.43185912, -0.24202311,  0.53892975, -1.00118258, -2.1352372 ,
        1.95927361, -1.95182625, -1.20753582, -1.32674697,  0.50363841,
        0.05690822, -1.20903743, -1.91917719, -1.77861819,  0.08879947,
        0.0656627 , -1.59611873, -0.41957308,  0.87749272,  0.99477257,
       -0.04706865, -1.15163466, -0.87458215, -1.35397831, -1.31

In [4]:
A = 10*A +50

In [5]:
A

array([37.38462157, 33.18955369, 61.53415272, 48.94041041, 50.38524076,
       65.03997163, 46.77223243, 58.25837298, 57.09384307, 48.04913335,
       68.5863897 , 60.87797465, 37.76271935, 48.3012984 , 64.73802597,
       52.33894521, 43.2819211 , 49.13113858, 64.71956985, 57.14790198,
       55.59236139, 38.40605116, 57.96655422, 50.48951386, 56.24497702,
       44.53496027, 52.94594781, 54.4576687 , 60.16220443, 50.79973257,
       30.08717329, 61.37745699, 37.91249143, 43.68722437, 54.50463321,
       53.32532221, 48.69094462, 53.12528613, 60.74171638, 30.49436948,
       61.0445206 , 43.97125921, 43.46964894, 51.77845726, 43.15134068,
       35.68140882, 47.57976893, 55.38929751, 39.98817416, 28.64762797,
       69.59273607, 30.48173745, 37.92464175, 36.73253034, 55.03638411,
       50.56908225, 37.90962566, 30.80822809, 32.21381815, 50.8879947 ,
       50.65662704, 34.03881268, 45.8042692 , 58.7749272 , 59.94772574,
       49.5293135 , 38.48365342, 41.25417852, 36.46021693, 36.83

## 改變Array維度
# array name.shape 可以看array的形狀

In [6]:
A.shape

(100,)

In [7]:
A.shape = (5, 20)

In [8]:
A

array([[37.38462157, 33.18955369, 61.53415272, 48.94041041, 50.38524076,
        65.03997163, 46.77223243, 58.25837298, 57.09384307, 48.04913335,
        68.5863897 , 60.87797465, 37.76271935, 48.3012984 , 64.73802597,
        52.33894521, 43.2819211 , 49.13113858, 64.71956985, 57.14790198],
       [55.59236139, 38.40605116, 57.96655422, 50.48951386, 56.24497702,
        44.53496027, 52.94594781, 54.4576687 , 60.16220443, 50.79973257,
        30.08717329, 61.37745699, 37.91249143, 43.68722437, 54.50463321,
        53.32532221, 48.69094462, 53.12528613, 60.74171638, 30.49436948],
       [61.0445206 , 43.97125921, 43.46964894, 51.77845726, 43.15134068,
        35.68140882, 47.57976893, 55.38929751, 39.98817416, 28.64762797,
        69.59273607, 30.48173745, 37.92464175, 36.73253034, 55.03638411,
        50.56908225, 37.90962566, 30.80822809, 32.21381815, 50.8879947 ],
       [50.65662704, 34.03881268, 45.8042692 , 58.7749272 , 59.94772574,
        49.5293135 , 38.48365342, 41.25417852, 3

In [9]:
A.reshape(100,1)

array([[37.38462157],
       [33.18955369],
       [61.53415272],
       [48.94041041],
       [50.38524076],
       [65.03997163],
       [46.77223243],
       [58.25837298],
       [57.09384307],
       [48.04913335],
       [68.5863897 ],
       [60.87797465],
       [37.76271935],
       [48.3012984 ],
       [64.73802597],
       [52.33894521],
       [43.2819211 ],
       [49.13113858],
       [64.71956985],
       [57.14790198],
       [55.59236139],
       [38.40605116],
       [57.96655422],
       [50.48951386],
       [56.24497702],
       [44.53496027],
       [52.94594781],
       [54.4576687 ],
       [60.16220443],
       [50.79973257],
       [30.08717329],
       [61.37745699],
       [37.91249143],
       [43.68722437],
       [54.50463321],
       [53.32532221],
       [48.69094462],
       [53.12528613],
       [60.74171638],
       [30.49436948],
       [61.0445206 ],
       [43.97125921],
       [43.46964894],
       [51.77845726],
       [43.15134068],
       [35

## reshape是另外產生一個array

In [10]:
A

array([[37.38462157, 33.18955369, 61.53415272, 48.94041041, 50.38524076,
        65.03997163, 46.77223243, 58.25837298, 57.09384307, 48.04913335,
        68.5863897 , 60.87797465, 37.76271935, 48.3012984 , 64.73802597,
        52.33894521, 43.2819211 , 49.13113858, 64.71956985, 57.14790198],
       [55.59236139, 38.40605116, 57.96655422, 50.48951386, 56.24497702,
        44.53496027, 52.94594781, 54.4576687 , 60.16220443, 50.79973257,
        30.08717329, 61.37745699, 37.91249143, 43.68722437, 54.50463321,
        53.32532221, 48.69094462, 53.12528613, 60.74171638, 30.49436948],
       [61.0445206 , 43.97125921, 43.46964894, 51.77845726, 43.15134068,
        35.68140882, 47.57976893, 55.38929751, 39.98817416, 28.64762797,
        69.59273607, 30.48173745, 37.92464175, 36.73253034, 55.03638411,
        50.56908225, 37.90962566, 30.80822809, 32.21381815, 50.8879947 ],
       [50.65662704, 34.03881268, 45.8042692 , 58.7749272 , 59.94772574,
        49.5293135 , 38.48365342, 41.25417852, 3

In [11]:
A = A.reshape(100,1)

In [12]:
A

array([[37.38462157],
       [33.18955369],
       [61.53415272],
       [48.94041041],
       [50.38524076],
       [65.03997163],
       [46.77223243],
       [58.25837298],
       [57.09384307],
       [48.04913335],
       [68.5863897 ],
       [60.87797465],
       [37.76271935],
       [48.3012984 ],
       [64.73802597],
       [52.33894521],
       [43.2819211 ],
       [49.13113858],
       [64.71956985],
       [57.14790198],
       [55.59236139],
       [38.40605116],
       [57.96655422],
       [50.48951386],
       [56.24497702],
       [44.53496027],
       [52.94594781],
       [54.4576687 ],
       [60.16220443],
       [50.79973257],
       [30.08717329],
       [61.37745699],
       [37.91249143],
       [43.68722437],
       [54.50463321],
       [53.32532221],
       [48.69094462],
       [53.12528613],
       [60.74171638],
       [30.49436948],
       [61.0445206 ],
       [43.97125921],
       [43.46964894],
       [51.77845726],
       [43.15134068],
       [35