### len, for迴圈使用

In [9]:
s = "今天是2019年3月6日"
s

'今天是2019年3月6日'

In [3]:
print(len(s))

12


In [4]:
for i in range(len(s)):
    print("i:", i, " 字串=", s[i])

i: 0  字串= 今
i: 1  字串= 天
i: 2  字串= 是
i: 3  字串= 2
i: 4  字串= 0
i: 5  字串= 1
i: 6  字串= 9
i: 7  字串= 年
i: 8  字串= 3
i: 9  字串= 月
i: 10  字串= 6
i: 11  字串= 日


In [5]:
s2 = ["今","天",'是','2','0','1','9','年','3','月','6','日']

In [7]:
print(len(s2))

12


In [8]:
for i in range(len(s2)):
    print("i:", i, " 字串=", s[i])

i: 0  字串= 今
i: 1  字串= 天
i: 2  字串= 是
i: 3  字串= 2
i: 4  字串= 0
i: 5  字串= 1
i: 6  字串= 9
i: 7  字串= 年
i: 8  字串= 3
i: 9  字串= 月
i: 10  字串= 6
i: 11  字串= 日


## tab的重要性

In [10]:
import numpy as np

In [11]:
a = np.zeros([3,3])

In [14]:
for i in range(3):
    for j in range(3):
        print("i:", i, "j:", j)
        a[i][j]=i*j

print(a)

i: 0 j: 0
i: 0 j: 1
i: 0 j: 2
i: 1 j: 0
i: 1 j: 1
i: 1 j: 2
i: 2 j: 0
i: 2 j: 1
i: 2 j: 2
[[0. 0. 0.]
 [0. 1. 2.]
 [0. 2. 4.]]
