# 能不用迴圈就不用迴圈 太耗時間

In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

In [2]:
p = [1096.95, 596.95, 896.95]

In [3]:
c = 30.1

In [4]:
prices = np.array(p)

## 把list轉換成numpy array的方法
# np.array(list name)
# array 可以做類似向量的計算

In [6]:
prices

array([1096.95,  596.95,  896.95])

In [7]:
print(prices)

[1096.95  596.95  896.95]


In [9]:
prices * c

array([33018.195, 17968.195, 26998.195])